#!/bin/bash
set -eo pipefail

source ../config/dap.config
source ../config/utils.sh

announce "Deleting Secretless deployment."
$CLI delete secret test-app-secret -n $TEST_APP_NAMESPACE_NAME --ignore-not-found 
$CLI delete secret dockerpullsecret -n $TEST_APP_NAMESPACE_NAME --ignore-not-found 

$CLI delete --ignore-not-found \
     -n $TEST_APP_NAMESPACE_NAME \
     service/postgres-db \
     statefulset/postgres-db \
     service/mysql-db \
     statefulset/mysql-db \
     service/nginx \
     statefulset/nginx  \
     deployment/test-app-secretless \
     service/test-app-secretless \
     service/test-secretless-app-backend \
     configmap/test-app-secretless-config \
     serviceaccount/$SECRETLESS_SERVICEACCOUNT_NAME \
     &

echo "Waiting for pods to terminate"
while [[ "$($CLI get pods -n $TEST_APP_NAMESPACE_NAME | grep postgres)" != "" ]]; do
  sleep 4
  echo -n '.'
done
echo

echo "Secretless app deleted."
