apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"conjur-follower"},"name":"conjur-follower","namespace":"conjur-follower"},"spec":{"ports":[{"name":"https","port":443,"protocol":"TCP","targetPort":443}],"selector":{"app":"conjur-follower"},"type":"ClusterIP"}}
    creationTimestamp: 2019-06-05T18:39:12Z
    labels:
      app: conjur-follower
    name: conjur-follower
    namespace: conjur-follower
    resourceVersion: "340053759"
    selfLink: /api/v1/namespaces/conjur-follower/services/conjur-follower
    uid: 36c66ff2-87c1-11e9-8ee3-0a00df8bcee6
  spec:
    clusterIP: 172.26.26.120
    ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: 443
    selector:
      app: conjur-follower
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
apiVersion: v1
items:
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: 2019-06-05T18:34:00Z
    generation: 9
    name: conjur-follower
    namespace: conjur-follower
    resourceVersion: "340104117"
    selfLink: /apis/apps.openshift.io/v1/namespaces/conjur-follower/deploymentconfigs/conjur-follower
    uid: 7c51a817-87c0-11e9-ad91-0649b57ee664
  spec:
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      app: conjur-follower
      name: conjur-follower
      role: follower
    strategy:
      activeDeadlineSeconds: 21600
      resources:
        limits:
          cpu: "1"
          memory: 512Mi
        requests:
          cpu: "1"
          memory: 512Mi
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: conjur-follower
          name: conjur-follower
          role: follower
      spec:
        containers:
        - env:
          - name: CONJUR_AUTHENTICATORS
            value: authn-k8s/dev1
          image: docker-registry.default.svc.cluster.local:5000/conjur-follower/conjur-follower:5.3.1
          imagePullPolicy: IfNotPresent
          name: conjur-appliance
          ports:
          - containerPort: 443
            name: https
            protocol: TCP
          - containerPort: 5432
            name: pg-main
            protocol: TCP
          - containerPort: 1999
            name: pg-audit
            protocol: TCP
          resources:
            limits:
              cpu: "2"
              memory: 4Gi
            requests:
              cpu: "2"
              memory: 4Gi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        serviceAccount: conjur-cluster
        serviceAccountName: conjur-cluster
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: 2019-06-05T20:03:33Z
      lastUpdateTime: 2019-06-05T20:03:33Z
      message: replication controller "conjur-follower-7" successfully rolled out
      reason: NewReplicationControllerAvailable
      status: "True"
      type: Progressing
    - lastTransitionTime: 2019-06-05T20:05:23Z
      lastUpdateTime: 2019-06-05T20:05:23Z
      message: Deployment config has minimum availability.
      status: "True"
      type: Available
    details:
      causes:
      - type: Manual
      message: manual change
    latestVersion: 7
    observedGeneration: 9
    readyReplicas: 1
    replicas: 1
    unavailableReplicas: 0
    updatedReplicas: 1
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
