# Define project namespace
---
apiVersion: v1
kind: Namespace
metadata:
  name: cyberark
  labels:
    name: cyberark

# Role binding to cluster role enabling developer to access the DAP config map
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dap-cm-access-binding
  namespace: cyberark
subjects:
- kind: User
  name: developer
roleRef:
  kind: ClusterRole
  name: dap-cmaccess
  apiGroup: rbac.authorization.k8s.io

# Grant project admin privileges to developer
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: project-admin-access-binding
  namespace: cyberark
subjects:
- kind: User
  name: developer
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io

# Grant image-builder privileges to developer
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: project-image-builder-binding
  namespace: cyberark
subjects:
- kind: User
  name: developer
roleRef:
  kind: ClusterRole
  name: system:image-builder
  apiGroup: rbac.authorization.k8s.io

# Grant registry privileges to developer
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: project-registry-binding
  namespace: cyberark
subjects:
- kind: User
  name: developer
roleRef:
  kind: ClusterRole
  name: system:registry
  apiGroup: rbac.authorization.k8s.io
