apiVersion: v1
kind: Pod
metadata:
  name: conjur-egress-1
  labels:
    name: conjur-egress
  annotations:
    pod.network.openshift.io/assign-macvlan: "true" 
spec:
  hostNetwork: true
  containers:
  - name: egress-router
    image: registry.access.redhat.com/openshift3/ose-egress-router
    securityContext:
      privileged: true
    env:
    - name: EGRESS_SOURCE 
      value: 192.168.99.102
    - name: EGRESS_GATEWAY 
      value: 192.168.99.102
    - name: EGRESS_DESTINATION 
      value: 192.168.99.102
