#!/bin/bash -x
# Manual deployment steps from:
# https://github.com/cyberark/sidecar-injector#installing-the-sidecar-injector-manually

NAMESPACE=injectors
TMPDIR=/tmp
LABEL=cyberark-sidecar-injector

./stop

# create namespace for injectors
kubectl create namespace $NAMESPACE

./deployment/webhook-create-signed-cert.sh \
    --service $LABEL \
    --secret $LABEL \
    --namespace $NAMESPACE

# Patch the MutatingWebhookConfiguration - set caBundle cluster value
cat deployment/mutatingwebhook.yaml |    	\
  deployment/webhook-patch-ca-bundle.sh  	\
   --namespace-selector-label $LABEL 		\
   --service $LABEL				\
   --namespace $NAMESPACE >  			\
   deployment/mutatingwebhook-ca-bundle.yaml

kubectl -n injectors apply -f deployment/deployment.yaml
kubectl -n injectors apply -f deployment/service.yaml
kubectl -n injectors apply -f deployment/mutatingwebhook-ca-bundle.yaml
kubectl -n injectors get pods
