FROM centos:latest

RUN     yum update &&\
        yum install -qy apt-utils dpkg libexpat1-dev libpython2.7-dev python2.7-dev vim &&\
        rm -rf /var/lib/apt/lists/* &&\
	yum update && \
        yum install -qy ruby-dev rubygems build-essential && \
        gem install conjur-cli -v 6.1.0
