---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ocp-appserver
---
apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    app: appserver
  name: appserver
spec:
  replicas: 1
  selector:
    app: appserver
  template:
    metadata:
      labels:
        app: appserver
    spec:
      serviceAccountName: ocp-appserver
      containers:
      - image: {{ TEST_APP_DOCKER_IMAGE }}
        imagePullPolicy: {{ IMAGE_PULL_POLICY }}
        name: test-app
        env:
          - name: CONJUR_APPLIANCE_URL
            value: "{{ CONJUR_APPLIANCE_URL }}"
          - name: CONJUR_ACCOUNT
            value: {{ CONJUR_ACCOUNT }}
          - name: CONJUR_SSL_CERTIFICATE
            valueFrom:
              configMapKeyRef:
                name: {{ CONFIG_MAP_NAME }}
                key: ssl-certificate
          - name: CONJUR_AUTHN_TOKEN_FILE
            value: /run/conjur/access-token
          - name: CONJUR_VERSION
            value: "{{ CONJUR_VERSION }}"
        volumeMounts:
          - mountPath: /run/conjur
            name: conjur-access-token
            readOnly: true
      - image: {{ AUTHENTICATOR_CLIENT_IMAGE }}
        imagePullPolicy: {{ IMAGE_PULL_POLICY }}
        name: authenticator
        env:
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: CONJUR_VERSION
            value: '{{ CONJUR_VERSION }}'
          - name: CONJUR_APPLIANCE_URL
            value: "{{ CONJUR_APPLIANCE_URL }}"
          - name: CONJUR_AUTHN_URL
            value: "{{ CONJUR_AUTHN_URL }}"
          - name: CONJUR_ACCOUNT
            value: {{ CONJUR_ACCOUNT }}
          - name: CONJUR_AUTHN_LOGIN
            value: "{{ CONJUR_AUTHN_LOGIN_PREFIX }}/ocp-appserver"
          - name: CONJUR_SSL_CERTIFICATE
            valueFrom:
              configMapKeyRef:
                name: {{ CONFIG_MAP_NAME }}
                key: ssl-certificate
        volumeMounts:
          - mountPath: /run/conjur
            name: conjur-access-token
      imagePullSecrets:
        - name: dockerpullsecret
      volumes:
        - name: conjur-access-token
          emptyDir:
            medium: Memory
