#!/bin/bash -eu

# Generate root and intermediate CA certificates

if [ ! -d ca/ca ]; then
  docker-compose run --rm ca
fi

auth_header=$(docker exec -it conjur-cli conjur authn authenticate -H) 

echo Store the intermediate CA private key in Conjur...
set -x
curl --cacert ${CONJUR_CERT_FILE} \
     --data-binary '@ca/ca/intermediate.key' \
     -H "$auth_header" \
     "${CONJUR_APPLIANCE_URL}/secrets/${CONJUR_ACCOUNT}/variable/conjur/mutual-tls/ca/private-key"

exit

echo Store the intermediate certificate chain in Conjur...
curl --cacert ${CONJUR_CERT_FILE} \
     --data-binary "@ca/ca/ca-chain.crt" \
     -H "$auth_header" \
     "${CONJUR_APPLIANCE_URL}/secrets/${CONJUR_ACCOUNT}/variable/conjur/mutual-tls/ca/cert-chain"

rm -rf server/ca-chain.crt client/ca-chain.crt
cp ca/ca/ca-chain.crt server/ca-chain.crt
cp ca/ca/ca-chain.crt client/ca-chain.crt
