apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: cyberark-sidecar-injector
  labels:
    app: cyberark-sidecar-injector
webhooks:
  - name: sidecar-injector.cyberark.com
    clientConfig:
      service:
        name: cyberark-sidecar-injector
        namespace: injectors
        path: "/mutate"
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM1ekNDQWMrZ0F3SUJBZ0lCQVRBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwdGFXNXAKYTNWaVpVTkJNQjRYRFRFNU1EVXhNREUyTVRBeU9Gb1hEVEk1TURVd056RTJNVEF5T0Zvd0ZURVRNQkVHQTFVRQpBeE1LYldsdWFXdDFZbVZEUVRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBS2dDCnlHR0U3V2Yzd0lnT29ickFFRG9CL0laUXNuNzZBeXllTnlEVmYrVVYrSjJFSXhueGNsSXVudFdWYisra3NJMkwKYk5pUGRZMFZYc3M0bVQzdXFCUnF5RWo0bmpBdUF2Z05pRHA1b2NlL252SVBId3VOZU5IQlFqcUFSZlA1a25FKwpRclFhY2ZUU0tRVEFnK0FtekdDTmFsRzV2WE5Dbk92MVBTdXJCV2tTWHRZN0Q5blM1K0F1K3IzcTVDMGJUMkVoCjVrZGV2eVprUzVVeXl6K0ROQ2JYMUVlc0I2KzdSOGk5YjZabGg3VUlWd0JHdGFXQjdEbEgvdWdaejdhZStTL1cKaTBHSXhWUUo1UUxodUFTSjlBcmNGMURpSUVLaG5lbTA4azdSaEZWb3FhUnlVUENFU0Q2V3EydXZjNUw1RlVrVwp6YnpVazBOMWpXZmZRd2VtdlQ4Q0F3RUFBYU5DTUVBd0RnWURWUjBQQVFIL0JBUURBZ0trTUIwR0ExVWRKUVFXCk1CUUdDQ3NHQVFVRkJ3TUNCZ2dyQmdFRkJRY0RBVEFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQTBHQ1NxR1NJYjMKRFFFQkN3VUFBNElCQVFBVlE5SHhXTlFGampFRWQva0l6MHA0MG5oWTh5ZmRhZWRFbFdXSUl4Q2g4ODlyekZFSQpmYk44SXRsaUxVeXpCVE8yNzhxVFVhY1FOdkcrL2xpRWJUQUtsQWJIVVN3c21wSlNqcXQ2aVVZRXVUZkQycTBpClpIMENrUUlHMFZ6Vzk1eGI4dC9jdW9ieEdpWFVtRFNKejc2RXh3cy82NFlCU1RKcTViaXNDUSs3STVnby9WZlYKZW4yajZhZmtpVUIxVzc2eHNsdm5EalprQlhQWGtpcGV4Y1FwQjQvNlRIYmtIMDZOMStjSE04VURlYVZnUHBjNQpuMHZGdXZEeWViMDVYR010dEVHaGliQUNDRFZvL3ZtN1lTTnd5TXY1QUczQU5MVXJsdkdPTzNoRkZaREtNOE1jCi9ESEdKUnNVdUZ2bmpPK1RjY29WRDBRWmJWSmFITW5mcU9BMgotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    rules:
      - operations: [ "CREATE" ]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    namespaceSelector:
      matchLabels:
        cyberark-sidecar-injector: enabled
