apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: cyberark-sidecar-injector
  labels:
    app: cyberark-sidecar-injector
webhooks:
  - name: sidecar-injector.cyberark.com
    clientConfig:
      service:
        name: cyberark-sidecar-injector
        namespace: test-injectors
        path: "/mutate"
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURDekNDQWZPZ0F3SUJBZ0lRWmNleXc1U2xwd1ZTT0xxdUpHWGFnVEFOQmdrcWhraUc5dzBCQVFzRkFEQXYKTVMwd0t3WURWUVFERXlSbU5tTTRNekl4TXkwMFlqTTJMVFF6TjJRdE9EWXlOUzAyTXpjeVpUY3pNV0kxWkRndwpIaGNOTVRnd01qRTBNVEl5TmpBMldoY05Nak13TWpFek1UTXlOakEyV2pBdk1TMHdLd1lEVlFRREV5Um1ObU00Ck16SXhNeTAwWWpNMkxUUXpOMlF0T0RZeU5TMDJNemN5WlRjek1XSTFaRGd3Z2dFaU1BMEdDU3FHU0liM0RRRUIKQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUURTQzhYS3kwWkl2VU5FWW1UeGF5T1pDeGhMMjBHZEczck1zaXl5blNXVwpCeU1DRTVDMURyMjB3bXRVY0MzUWM5eUV1V29GbUpzRTZrWHhkUFZCMnFLQ3hXZHFSYTR3NGhKSUZiSDl5ei83ClFYNllyQi9ySnJHb25SbE9VaWZ4VUlZSmQ1MGVOWS9uekxVZzFoQXp0YkwydmNyTVdZNUNCbmJPbFFxdjNCbzAKS01GVHgvQnVRY204OFhwMXk4TDNHcENwc3FERUNJSGRGaVNFdXFCM0ZheDJhUGFOcVZ5V0p2RlZZNitaN3l0agpoaHc3N0E1amdoUVB0NWFWbWZIdzJVUjdUQVBHT1oyNXBLNGJsV2tMOExGckwwWlRGd2JzZ213dkMxcDR5SUw3CkQ1SUNZRkF5anFZY2w5SE9lbmgxSFhrOHllRUJKSUdsd04yU1lQdVpjeHZMQWdNQkFBR2pJekFoTUE0R0ExVWQKRHdFQi93UUVBd0lDQkRBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCQVFEUApDYWtib2djTGNtdkpDb3Y4R2E5cnpTSXZzNGpOTGNTeG53STdRYmhDT1cvaWRzWFgwUmUvUTd3eGIzclhGeUVRCnc2RHBUZHF1SkI0MmFWazZBbEtjMi95Mkh3WHUxWmpMQnV6Wmo0dWd1c0F6cCs2alNQS0ROZHROdm0xSmxZMm0KVmJJWGU1QXZQSEtreStRZ2UzT3luMkNrVXVKMTlLT2gwazZsSFkraTlkSHU5WndBeFJjZEMvWmhvSElQSEpJSwptayt4eTc4Ulc2azE3MTgyRU9TSE5WWmVnSHQ0eVdsUzk5cnJZQUtiamtYY2gzL0MvT1VQYlJkU1NlSGhEV2IwCjVoV0tYTDYxaGVaMjJ1QWc2WXc3SGo3KzMyWjlhSko3MlFhZ0ZkdkVUWU0wMkRWWGVUV3ZaMC9BNEVVelBxQjEKZEo2MlZ6QTB2Y0M3M3EzNTVGZXkKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    rules:
      - operations: [ "CREATE" ]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    namespaceSelector:
      matchLabels:
        cyberark-sidecar-injector: enabled
