---
kind: Service
apiVersion: v1
metadata:
  name: mysql-db
  namespace: {{ TEST_APP_NAMESPACE_NAME }}
spec:
  selector:
    app: mysql-db
  ports:
    - port: 3306
      targetPort: 3306

---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: mysql-db
  labels:
    app: mysql-db
spec:
  serviceName: mysql-db
  selector:
    matchLabels:
      app: mysql-db
  template:
    metadata:
      labels:
        app: mysql-db
    spec:
      containers:
      - name: mysql-db
        image: centos/mysql-57-centos7
        imagePullPolicy: {{ IMAGE_PULL_POLICY }}
        ports:
          - containerPort: 3306
        env:
          - name: MYSQL_USER
            value: test_app
          - name: MYSQL_PASSWORD
            value: {{ TEST_APP_DB_PASSWORD }}
          - name: MYSQL_DATABASE
            value: test_app
