---
kind: Service
apiVersion: v1
metadata:
  name: postgres-db
  namespace: {{ TEST_APP_NAMESPACE_NAME }}
spec:
  selector:
    app: postgres-db
  ports:
    - port: 5432
      targetPort: 5432

---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: postgres-db
  labels:
    app: postgres-db
spec:
  serviceName: postgres-db
  selector:
    matchLabels:
      app: postgres-db
  template:
    metadata:
      labels:
        app: postgres-db
    spec:
      containers:
      - name: postgres-db
        image: centos/postgresql-95-centos7
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 5432
        env:
          - name: POSTGRESQL_USER
            value: test_app
          - name: POSTGRESQL_PASSWORD
            value: {{ TEST_APP_DB_PASSWORD }}
          - name: POSTGRESQL_DATABASE
            value: test_app
        command: ["/bin/sh", "-c", "run-postgresql" ]
