---
apiVersion: v1
kind: Service
metadata:
  name: test-app-secretless
  labels:
    app: test-app-secretless
spec:
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  selector:
    app: test-app-secretless
  type: LoadBalancer

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ocp-secretless-broker

---
apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    app: test-app-secretless
  name: test-app-secretless
spec:
  replicas: 1
  selector:
    app: test-app-secretless
  template:
    metadata:
      labels:
        app: test-app-secretless
    spec:
      serviceAccountName: ocp-secretless-broker
      containers:
      - image: {{ SECRETLESS_APP_IMAGE }}
        imagePullPolicy: {{ IMAGE_PULL_POLICY }}
        name: test-app-secretless
        ports:
        - name: http
          containerPort: 8080

#        readinessProbe:
#          httpGet:
#            path: /pets
#            port: http
#          initialDelaySeconds: 15
#          timeoutSeconds: 5
        env:
          - name: DB_URL
            value: postgresql://localhost:5432/test_app?sslmode=disable
          - name: DB_USERNAME
            value: user
          - name: DB_PASSWORD
            value: password
          - name: DB_CSTRING
            value: postgresql://user:password@localhost:5432/test_app?sslmode=disable
      - image: {{ SECRETLESS_BROKER_IMAGE }}
        imagePullPolicy: {{ IMAGE_PULL_POLICY }}
        name: secretless
        # args refer to values mounted from config map, populated from Conjur
        args: ["-f", "/etc/secretless/secretless.yml"]
        ports:
        - containerPort: 5432
        env:
          - name: CONJUR_VERSION
            value: "{{ CONJUR_VERSION }}"
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: CONJUR_AUTHN_URL
            value: "{{ CONJUR_AUTHN_URL }}"
          - name: CONJUR_APPLIANCE_URL
            value: "{{ CONJUR_APPLIANCE_URL }}"
          - name: CONJUR_ACCOUNT
            value: "{{ CONJUR_ACCOUNT }}"
          - name: CONJUR_AUTHN_LOGIN
            value: "{{ CONJUR_AUTHN_LOGIN_PREFIX }}/ocp-secretless-broker"
          - name: CONJUR_SSL_CERTIFICATE
            valueFrom:
              configMapKeyRef:
                name: "{{ CONFIG_MAP_NAME }}"
                key: ssl-certificate
        volumeMounts:
        - name: config
          mountPath: "/etc/secretless"
          readOnly: true
      imagePullSecrets:
        - name: dockerpullsecret
      volumes:
      - name: config
        configMap:
          name: test-app-secretless-config
