#!/bin/bash 

source ../config/dap.config
source ./vault-sync.config

sed -e "s#{{ VAULT_NAME }}#$VAULT_NAME#g" \
  ./vault-sync-policy.template |
  sed -e "s#{{ SYNC_HOST }}#$SYNC_HOST#g" \
  > vault-sync-policy.yml
load_policy_REST.sh root vault-sync-policy.yml 
echo "API key for $SYNC_HOST:" $(docker exec conjur-cli conjur host rotate_api_key -h $SYNC_HOST)
