apiVersion: v1
kind: Service
metadata:
  name: test-app-secretless
  labels:
    app: test-app-secretless
spec:
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  selector:
    app: test-app-secretless
  type: LoadBalancer
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ SECRETLESS_SERVICEACCOUNT_NAME }}
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: test-app-secretless
  name: test-app-secretless
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-app-secretless
  template:
    metadata:
      labels:
        app: test-app-secretless
    spec:
      serviceAccountName: {{ SECRETLESS_SERVICEACCOUNT_NAME }}
      containers:
      - image: {{ SECRETLESS_APP_IMAGE }}
        imagePullPolicy: {{ IMAGE_PULL_POLICY }}
        name: test-app-secretless
        ports:
        - name: http
          containerPort: 8080
#        readinessProbe:
#          httpGet:
#            path: /pets
#            port: http
#          initialDelaySeconds: 15
#          timeoutSeconds: 5

        env:
          - name: DB_URL
            value: postgresql://localhost/test_app
          - name: DB_USERNAME
            value: ignore
          - name: DB_PASSWORD
            value: ignore
          - name: CONN_SSH
            value: "-p 2222 foo@localhost"
          - name: CONN_PG
            value: "postgresql://ignore:ignore@localhost/test_app"
          - name: CONN_MS
            value: "-h 127.0.0.1 -u ignore -pignore test_app"
          - name: CONN_HTTP
            value: "http://nginx:8081"
          - name: http_proxy
            value: "http://localhost:8081"
      - image: {{ SECRETLESS_BROKER_IMAGE }}
        imagePullPolicy: {{ IMAGE_PULL_POLICY }}
        name: secretless
        # args refer to values mounted from config map, populated from Conjur
        args: ["-f", "/etc/secretless/secretless.yml"]
        env:

        # values from pod metadata
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP

        # values from DAP config map
          - name: CONJUR_VERSION
            valueFrom:
              configMapKeyRef:
                name: "{{ CONJUR_CONFIG_MAP }}"
                key: conjur-version
          - name: CONJUR_ACCOUNT
            valueFrom:
              configMapKeyRef:
                name: "{{ CONJUR_CONFIG_MAP }}"
                key: conjur-account
          - name: CONJUR_APPLIANCE_URL
            valueFrom:
              configMapKeyRef:
                name: "{{ CONJUR_CONFIG_MAP }}"
                key: conjur-follower-url
          - name: CONJUR_SSL_CERTIFICATE
            valueFrom:
              configMapKeyRef:
                name: "{{ CONJUR_CONFIG_MAP }}"
                key: follower-certificate

        # values from app config map
          - name: CONJUR_AUTHN_URL
            valueFrom:
              configMapKeyRef:
                name: "{{ APP_CONFIG_MAP }}"
                key: conjur-authn-url
          - name: CONJUR_AUTHN_LOGIN
            valueFrom:
              configMapKeyRef:
                name: "{{ APP_CONFIG_MAP }}"
                key: conjur-authn-login

        volumeMounts:
        - name: config
          mountPath: "/etc/secretless"
          readOnly: true
      imagePullSecrets:
        - name: dockerpullsecret
      volumes:
      - name: config
        configMap:
          name: test-app-secretless-config
