#!/bin/bash
set -eo pipefail

. utils.sh

if [ $PLATFORM = 'openshift' ]; then
  oc login -u $OSHIFT_CLUSTER_ADMIN_USERNAME
fi

if ! has_namespace $TEST_APP_NAMESPACE_NAME; then
  exit 0
fi

set_namespace $TEST_APP_NAMESPACE_NAME

announce "Deleting secrets."
if [ $PLATFORM = 'kubernetes' ]; then
  kubectl delete --ignore-not-found secret test-app-secret
  if ! [ "${DOCKER_EMAIL}" = "" ]; then
    kubectl delete --ignore-not-found secret dockerpullsecret
  fi
elif [ $PLATFORM = 'openshift' ]; then
  oc delete --ignore-not-found secrets test-app-secret
  oc delete --ignore-not-found secrets dockerpullsecret
fi

announce "Deleting test app/sidecar deployment."
$cli delete --ignore-not-found \
  deployment/appserver \
  rc/appserver-1 \
  svc/appserver \
  sa/k8s-appserver \
  sa/ocp-appserver

if [ $PLATFORM = 'openshift' ]; then
  oc delete --ignore-not-found deploymentconfig/appserver
fi

announce "Deleting test app/init container deployment."
$cli delete --ignore-not-found \
  deployment/webserver \
  rc/webserver-1 \
  svc/webserver \
  sa/k8s-webserver \
  sa/ocp-webserver

if [ $PLATFORM = 'openshift' ]; then
  oc delete --ignore-not-found deploymentconfig/webserver
fi

echo "Waiting for pods to terminate"
while [[ "$($cli get pods | grep appserver)" != "" ]]; do
  sleep 4
  echo -n '.'
done
echo

echo "Test app deleted."
