#!/bin/bash -x
set -eo pipefail

. utils.sh

if [ $PLATFORM = 'openshift' ]; then
  oc login -u $OSHIFT_CLUSTER_ADMIN_USERNAME
fi

if ! has_namespace $TEST_APP_NAMESPACE_NAME; then
  exit 0
fi

set_namespace $TEST_APP_NAMESPACE_NAME

announce "Deleting secrets."
if [ $PLATFORM = 'kubernetes' ]; then
  kubectl delete --ignore-not-found secret test-app-secret
  if ! [ "${DOCKER_EMAIL}" = "" ]; then
    kubectl delete --ignore-not-found secret dockerpullsecret
  fi
elif [ $PLATFORM = 'openshift' ]; then
  oc delete --ignore-not-found secrets test-app-secret
  oc delete --ignore-not-found secrets dockerpullsecret
fi

announce "Deleting Secretless deployment."
  $cli delete --ignore-not-found \
     service/postgres-db \
     statefulset/postgres-db \
     service/mysql-db \
     statefulset/mysql-db \
     service/nginx \
     statefulset/nginx  \
     deployment/test-app-secretless \
     service/test-app-secretless \
     service/test-secretless-app-backend \
     configmap/test-app-secretless-config \
     serviceaccount/ocp-secretless-broker \
     serviceaccount/k8s-secretless-broker \
     &

if [ $PLATFORM = 'openshift' ]; then
  oc delete --ignore-not-found deploymentconfig/test-app-secretless
  oc delete --ignore-not-found routes/test-app-secretless
fi

echo "Waiting for pods to terminate"
while [[ "$($cli get pods | grep postgres)" != "" ]]; do
  sleep 4
  echo -n '.'
done
echo

echo "Secretless app deleted."
