version: "2"
services:

  tower:
    container_name: tower
    image: $TOWER_IMAGE_NAME
    build: ./build/tower
    restart: always
    ports:
    - $TOWER_INTERNAL_PORT:$TOWER_EXTERNAL_PORT

  pgsql:
    container_name: pgsql
    image: $PGSQL_IMAGE_NAME
    build: ./build/pgsql
    restart: always
