---
- !policy
  id: prod
  annotations:
    description: Prod root policy
  body:
  - !group admins

  - !group hosts

  - &variables
    - !variable common-prod-secret1
    - !variable common-prod-secret2

  - !permit
    privileges: [ read, execute ]
    roles:
    - !group hosts
    resources: *variables
