---
kind: Service
apiVersion: v1
metadata:
  name: postgres-db
  namespace: testapps
spec:
  selector:
    app: postgres-db
  ports:
    - port: 5432
      targetPort: 5432

---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: postgres-db
  labels:
    app: postgres-db
spec:
  serviceName: postgres-db
  selector:
    matchLabels:
      app: postgres-db
  template:
    metadata:
      labels:
        app: postgres-db
    spec:
      serviceAccountName: secretless-stateful-app
      securityContext:
        fsGroup: 999
      containers:
      - name: postgres-db
        imagePullPolicy: IfNotPresent
        image: 172.30.1.1:5000/pgsql:latest
        ports:
          - containerPort: 5432
        env:
          - name: POSTGRES_USER
            value: test_app
          - name: POSTGRES_PASSWORD
            value: 99cb8bdc670f853f993ecca3
          - name: POSTGRES_DB
            value: test_app
